name: SKOG302
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pandas=1.4.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - bzip2=1.0.8
  - libzip=1.8.0
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - numpy=1.21.5
  - numpy-base=1.21.5
  - pip=22.1.2
  - plotly=5.10.0
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - tqdm=4.64.0
  - pip:
    - wget==3.2
    - requests==2.28.1
    - shapely==1.8.2
    - umap==0.1.1
    - urllib3==1.26.11
    
